server:
  port: ${ACCOUNT_PORT}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${IDP_HOST}:${IDP_PORT}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${ACCOUNT_DATASOURCE_HOST}:${ACCOUNT_DB_PORT}/${ACCOUNT_DB}?characterEncoding=utf8
    username: postgres
    password: ${ACCOUNT_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update

axon:
  eventhandling:
    processors:
      name:
        mode: tracking

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG