version: "3"
services:
  idp_db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=${IDP_DB}
      - POSTGRES_PASSWORD=${IDP_DB_PASSWORD}
    ports:
      - "${IDP_DB_PORT}:5432"
  account_db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=${ACCOUNT_DB}
      - POSTGRES_PASSWORD=${ACCOUNT_DB_PASSWORD}
    ports:
      - "${ACCOUNT_DB_PORT}:5432"
  broker:
      image: rabbitmq:3-management
      ports:
        - "${BROKER_PORT}:5672"
        - "15672:15672" # Web management console
