version: "3"
services:
  idp_db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=${IDP_DB}
      - POSTGRES_PASSWORD=${IDP_DB_PASSWORD}
    ports:
      - "${IDP_DB_PORT}:5432"
  userdetails_db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=${USERDETAILS_DB}
      - POSTGRES_PASSWORD=${USERDETAILS_DB_PASSWORD}
    ports:
      - "${USERDETAILS_DB_PORT}:5432"
