version: "3"
services:
  idp_db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=${IDP_DB}
      - POSTGRES_PASSWORD=${IDP_DB_PASSWORD}
    ports:
      - "${IDP_DB_PORT}:5432"
  account_db:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=${ACCOUNT_DB}
      - POSTGRES_PASSWORD=${ACCOUNT_DB_PASSWORD}
    ports:
      - "${ACCOUNT_DB_PORT}:5432"
  axon:
    image: axoniq/axonserver
    ports:
      - "${AXON_PORT}:8024"
      - "${AXON_GATEWAY}:8124"