server:
  port: ${USERDETAILS_PORT}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${IDP_HOST}:${IDP_PORT}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${USERDETAILS_DATASOURCE_HOST}:${USERDETAILS_DB_PORT}/${USERDETAILS_DB}?characterEncoding=utf8
    username: postgres
    password: ${USERDETAILS_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update