server:
  port: ${GATEWAY_PORT}

spring:
  cloud:
    gateway:
      routes:
        - id: account
          uri: http://${ACCOUNT_HOST}:${ACCOUNT_PORT}
          predicates:
            - Path=${ACCOUNT_API}/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: ${GATEWAY_CLIENT_ID}
            client-secret: ${GATEWAY_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          spring:
            issuer-uri: http://${IDP_HOST}:${IDP_PORT}