spring:
  application:
    name: configuration-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/APletenev/config-server-repo
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          clone-on-start: true
    bus:
      enabled: true
    kafka:
      bootstrap-servers: ${BROKER_HOST}:${BROKER_PORT}

server:
  port: ${CONFIG_PORT}