server:
  port: ${IDP_PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${IDP_DATASOURCE_HOST}:${IDP_DB_PORT}/${IDP_DB}?characterEncoding=utf8
    username: postgres
    password: ${IDP_DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect=org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      platform: postgresql

  cloud:
    stream:
      bindings:
        signupEventSupplier-out-0:
          destination: signup-events
      source: signupEventSupplier

  rabbitmq:
    host=localhost
    port=5672
    username=guest
    password=guest

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG