server:
  port: ${IDP_PORT}

spring:

  application:
    name: idp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${IDP_DATASOURCE_HOST}:${IDP_DB_PORT}/${IDP_DB}?characterEncoding=utf8
    username: postgres
    password: ${IDP_DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect=org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      platform: postgresql

  cloud:
    stream:
      bindings:
        signup-out-0:
          destination: signup
        signup-in-0:
          destination: signup
          group: user1
      source: signup;accountCreation
      function:
        definition: accountCreation;signup
      kafka:
        streams:
          binder:
            functions:
              accountCreation:
                applicationId: account-creation-consumer
              signup:
                applicationId: signup-consumer

  kafka:
    bootstrap-servers:
      ${BROKER_HOST}: ${BROKER_PORT}

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG