server:
  port: ${IDP_PORT}

spring:

  application:
    name: idp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${IDP_DATASOURCE_HOST}:${IDP_DB_PORT}/${IDP_DB}?characterEncoding=utf8
    username: postgres
    password: ${IDP_DB_PASSWORD}

  config:
    import: configserver:http://${CONFIG_HOST}:${CONFIG_PORT}